python generate_error_plot.py --dimensions=256x256 --test_dimensions=256x256 --nr_downsamples=4 --base_dir=../checkpoints_show_case --filter_size=16 --filter_size_compression=128 --test_length=200 --test_nr_runs=10
python generate_error_plot.py --dimensions=256x256 --test_dimensions=1024x1024 --nr_downsamples=4 --base_dir=../checkpoints_show_case --filter_size=16 --filter_size_compression=128 --test_length=200 --test_nr_runs=5
